# Generated by Django 6.0.1 on 2026-04-06 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_score', models.FloatField(blank=True, null=True, verbose_name='Điểm chuyên cần')),
                ('regular_score', models.FloatField(blank=True, null=True, verbose_name='Điểm thường xuyên')),
                ('midterm_score', models.FloatField(blank=True, null=True, verbose_name='Điểm giữa kỳ')),
                ('final_score', models.FloatField(blank=True, null=True, verbose_name='Điểm cuối kỳ')),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.courseclass', verbose_name='Lớp học phần')),
            ],
            options={
                'verbose_name': 'Bảng điểm / Đăng ký',
                'verbose_name_plural': 'Bảng điểm / Đăng ký',
            },
        ),
    ]
