# Generated by Django 6.0.3 on 2026-03-25 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tên lớp sinh hoạt')),
                ('major', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chuyên ngành')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.studentclass', verbose_name='Lớp sinh hoạt'),
        ),
    ]
