# Generated by Django 6.0.3 on 2026-03-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_studentclass_user_student_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='regular_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Điểm thường xuyên'),
        ),
    ]
