# Generated by Django 6.0.1 on 2026-04-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=50, verbose_name='Phòng học')),
                ('schedule', models.CharField(max_length=100, verbose_name='Lịch học')),
            ],
            options={
                'db_table': 'core_courseclass',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên học kỳ')),
                ('is_active', models.BooleanField(default=False, verbose_name='Đang diễn ra')),
            ],
            options={
                'db_table': 'core_semester',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã môn')),
                ('name', models.CharField(max_length=100, verbose_name='Tên môn')),
                ('credits', models.IntegerField(verbose_name='Số tín chỉ')),
            ],
            options={
                'db_table': 'core_subject',
            },
        ),
    ]
